name = "suriez-kitchen"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist/public"

# Build configuration for Cloudflare Pages
[build]
command = "npm run build"
cwd = "."


# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "suriez-kitchen-db"
database_id = "492deff0-8881-4f9c-b8a7-f43fa94b2dd7"

# Environment variables
[vars]
NODE_ENV = "production"
SESSION_SECRET = "a39dac7a4a3286d0e93e64947f9a5aefc14d3e8026a5e2d240b4a393a8462f7c"

# YouTube API configuration (replace with your actual values)
# [vars]
YOUTUBE_API_KEY = "AIzaSyCba_FtraHaQNxCkJT4A7Im5MsXkMyNEZ8"
YOUTUBE_CHANNEL_ID = "UCsWnEV_XEevwZvSCpOLDkNw"
